import type { EditorI18nMessages } from '../types/editor';

/**
 * 英文编辑器语言包。
 */
export const enUSMessages: EditorI18nMessages = {
  placeholder: 'Type / to open the command menu...',
  initError: 'Editor initialization failed. Please refresh the page and try again.',
  editorAriaLabel: 'Markdown editor',
  mathBlockSourceAriaLabel: 'Math block source',
  mathBlockCopyAriaLabel: 'Copy math source',
  mathBlockDeleteAriaLabel: 'Delete math block',
  imageDeleteAriaLabel: 'Delete image',
  tableDeleteAriaLabel: 'Delete table',
  tableMoreAriaLabel: 'More table actions',
  tableAlignLeftAriaLabel: 'Align current column left',
  tableAlignCenterAriaLabel: 'Align current column center',
  tableAlignRightAriaLabel: 'Align current column right',
  tableInsertRowAboveLabel: 'Insert row above',
  tableInsertRowBelowLabel: 'Insert row below',
  tableInsertColumnLeftLabel: 'Insert column left',
  tableInsertColumnRightLabel: 'Insert column right',
  tableDeleteRowLabel: 'Delete row',
  tableDeleteColumnLabel: 'Delete column',
  mathRenderError: 'Formula rendering failed. Please check the formula syntax.',
  imageUploadDialogTitle: 'Insert image',
  imageUploadDropLabel: 'Drop an image here, or choose a file',
  imageUploadPickFileLabel: 'Choose file',
  imageUploadFileTab: 'Upload file',
  imageUploadUrlTab: 'Image URL',
  imageUploadUrlPlaceholder: 'Paste image URL',
  imageUploadInsertUrlLabel: 'Insert URL',
  imageUploadConfirmLabel: 'Confirm',
  imageUploadUploadingLabel: 'Uploading...',
  imageUploadCancelLabel: 'Cancel',
  imageUploadLoadFailed: 'Image failed to load',
  imageUploadReselectHint: 'Click or drag to reselect',
  imageUploadSupportsAndMax: 'Supports image files, max {size}',
  imageUploadFileTooLarge: 'The image file is too large.',
  imageUploadFileSizeExceeded: 'Image size must not exceed {size}',
  imageUploadInvalidType: 'Please choose an image file.',
  imageUploadFailed: 'Image upload failed. Please try again.',
  imageUploadFileReadFailed: 'File read failed. Please try again.',
  imageUploadInvalidUrl: 'Please enter a valid image URL.',
  imageUploadUrlRequired: 'Please enter an image URL.',
  imageUploadSelectOrEnterImage: 'Please select an image or enter an image URL.',
  imageUploadUploadingWait: 'Image is uploading, please wait.',
  selectionTooltipStrongTitle: 'Bold',
  selectionTooltipEmTitle: 'Italic',
  selectionTooltipStrikeTitle: 'Strikethrough',
  selectionTooltipInlineCodeTitle: 'Inline code',
  selectionTooltipLinkTitle: 'Link',
  selectionLinkInputPlaceholder: 'Type or paste a link',
  selectionLinkSaveAriaLabel: 'Save link',
  selectionLinkRemoveAriaLabel: 'Remove link',
  codeBlockLanguageSearchPlaceholder: 'Search languages',
  codeBlockLanguagePlainText: 'text',
  codeBlockCopyAriaLabel: 'Copy code block',
  codeBlockDeleteAriaLabel: 'Delete code block'
};
