import type { EditorI18nMessages } from '../types/editor';

/**
 * 中文编辑器语言包。
 */
export const zhCNMessages: EditorI18nMessages = {
  placeholder: '请输入 / 打开命令菜单...',
  initError: '编辑器初始化失败，请刷新页面后重试。',
  editorAriaLabel: 'Markdown 编辑器',
  mathBlockSourceAriaLabel: '公式块源码',
  mathBlockCopyAriaLabel: '复制公式源码',
  mathBlockDeleteAriaLabel: '删除公式块',
  tableDeleteAriaLabel: '删除表格',
  tableMoreAriaLabel: '更多表格操作',
  tableAlignLeftAriaLabel: '当前列左对齐',
  tableAlignCenterAriaLabel: '当前列居中对齐',
  tableAlignRightAriaLabel: '当前列右对齐',
  tableInsertRowAboveLabel: '上方插入行',
  tableInsertRowBelowLabel: '下方插入行',
  tableInsertColumnLeftLabel: '左侧插入列',
  tableInsertColumnRightLabel: '右侧插入列',
  tableDeleteRowLabel: '删除该行',
  tableDeleteColumnLabel: '删除该列',
  mathRenderError: '公式渲染失败，请检查公式语法。',
  imageUploadDialogTitle: '插入图片',
  imageUploadDropLabel: '拖拽图片到这里，或选择文件',
  imageUploadPickFileLabel: '选择文件',
  imageUploadFileTab: '上传文件',
  imageUploadUrlTab: '图片链接',
  imageUploadUrlPlaceholder: '粘贴图片链接',
  imageUploadInsertUrlLabel: '插入链接',
  imageUploadConfirmLabel: '确认',
  imageUploadUploadingLabel: '上传中...',
  imageUploadCancelLabel: '取消',
  imageUploadLoadFailed: '图片加载失败',
  imageUploadReselectHint: '点击或拖拽重新选择',
  imageUploadSupportsAndMax: '支持图片文件，最大 {size}',
  imageUploadFileTooLarge: '图片文件过大。',
  imageUploadFileSizeExceeded: '图片大小不能超过 {size}',
  imageUploadInvalidType: '请选择图片文件。',
  imageUploadFailed: '图片上传失败，请重试。',
  imageUploadFileReadFailed: '文件读取失败，请重试。',
  imageUploadInvalidUrl: '请输入有效的图片链接。',
  imageUploadUrlRequired: '请输入图片链接。',
  imageUploadSelectOrEnterImage: '请选择图片或输入图片链接。',
  imageUploadUploadingWait: '图片正在上传，请稍候。'
};
